spring:
  application:
    name: Shoes_Management
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Shoes_OnlineShopping?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: hoan2709

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    open-in-view: false

  # Java mail sender
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SUPPORT_EMAIL}
    password: ${APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    user:
      name: user
      password: $2a$10$x/uOvNKEQSr0tDNQF2TV9uSDbYOiHzh.Hx2dVaCq5b4ps3Auo9fte
  config:
    import: "optional:file:.env[.properties]"

  app:
    jwtExpirationMs: 3600000
    signerKey: 6SjMf1ukIpm75rRJgzNsbo7n2LqJWgKe+SwPqchr+IG2dLkqqY74TF1LSiOXRRdn